### ISSUE TITLE
[BUG] Phone crashed overnight

### ISSUE THREAD

**Issue by Skyterix1991** [ananjaser1211/FloydQ_Reports#7]
**Describe the bug**
My phone crashed overnight. When I woke I was met with my phone green led always shining even when I unplug the charger the phone was not responding, and I had to soft reset using POWER + VOL DOWN.

I tried collecting logs, but it appears they are only collected after the system start, and mine was ten minutes ago. I attached them anyway in case they will help you.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F

[log_e.log](https://github.com/ananjaser1211/FloydQ_8890/files/4508360/log_e.log)

**Comment by ananjaser1211** [comment]
KMSG of the same crash Attached :

[KMSG.log](https://github.com/ananjaser1211/FloydQ_8890/files/4508469/KMSG.log)

No clear scenario to what triggers this issue yet.

**Comment by Skyterix1991** [comment]
[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4508546/log_kmsg.log)

**Comment by ananjaser1211** [comment]
> [log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4508546/log_kmsg.log)

Thanks, i will try and compare the behaviour of both logs and see if i can figure it out.

The same bug occured with another user while using wireless charger

**Comment by laiya98** [comment]
i had same error

**Comment by Skyterix1991** [comment]
> i had same error

You should upload logs mentioned above here

**Comment by laiya98** [comment]
how to get logs it happenes last night.

**Comment by freakbox69** [comment]
Same here, wireless charging
[last_kmsg.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4510267/last_kmsg.zip)

**Comment by Skyterix1991** [comment]
> how to get logs it happenes last night.

https://github.com/ananjaser1211/FloydQ_8890
Follow instructions under "How to gather logs with LoggingKit" on the main page and you need to run log_kmsg to get those logs.

**Comment by freakbox69** [comment]
Same here, wireless charging
[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4510394/log_kmsg.log)

**Comment by hadi-84** [comment]
add network speed on status bar

**Comment by laiya98** [comment]
here is mine g935fd 
[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4513612/log_kmsg.log)

**Comment by Tomhet** [comment]
Happened to me as well, no wireless charging, original charger with Fast Charge on
[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4514534/log_kmsg.log)

**Comment by Skyterix1991** [comment]
Happened tonight too. I came to the conclusion that the ROM crashes after min. 30 min after the phone's battery full charge. I am also using the Fast Charge charger.

[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4515909/log_kmsg.log)

**Comment by ananjaser1211** [comment]
Suggestion. Can you recreate the crash with MoroKernel for Q

Download : https://androidfilehost.com/?fid=4349826312261770822

Please let me know,

**Comment by Skyterix1991** [comment]
Sure, I will let you know in the morning.

**Comment by Skyterix1991** [comment]
> Suggestion. Can you recreate the crash with MoroKernel for Q
> 
> Download : https://androidfilehost.com/?fid=4349826312261770822
> 
> Please let me know,

Still crashes

[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4519989/log_kmsg.log)

**Comment by ananjaser1211** [comment]
> > Suggestion. Can you recreate the crash with MoroKernel for Q
> > Download : https://androidfilehost.com/?fid=4349826312261770822
> > Please let me know,
> 
> Still crashes
> 
> [log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4519989/log_kmsg.log)

Thank you for testing, this saved me alot of time. 

After multiple logs, this `vfsspi_fp_homekey_ev : not set the retain pin!` seems to be occuring every single time before the the device is hard reseted.

while i investigate this further. could you please try to disable Adaptive fast charging in settings (you can do so by long pressing the "fast charging" in notification bar)
if you have done that already do let me know.

Thanks,

**Comment by Skyterix1991** [comment]
> > > Suggestion. Can you recreate the crash with MoroKernel for Q
> > > Download : https://androidfilehost.com/?fid=4349826312261770822
> > > Please let me know,
> > 
> > 
> > Still crashes
> > [log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4519989/log_kmsg.log)
> 
> Thank you for testing, this saved me alot of time.
> 
> After multiple logs, this `vfsspi_fp_homekey_ev : not set the retain pin!` seems to be occuring every single time before the the device is hard reseted.
> 
> while i investigate this further. could you please try to disable Adaptive fast charging in settings (you can do so by long pressing the "fast charging" in notification bar)
> if you have done that already do let me know.
> 
> edit : when you hard reset do you press voldown + power still or voldown + power + home
> 
> Thanks,

I disabled fast charging and so far so good. The phone is in full charge for two hours now. I will let you know later if something changes.

As for the combination, I press voldown + power + home. Never can remember which combination works :p

**Comment by fz75** [comment]
I noticed the same problem, for two nights in a row, with original wireless charger, AOD disabled, fast charging disabled! Now, with the same conditions, but with AOD active, 100% charged, green LED, no problem, phone ok !!!

**Comment by ananjaser1211** [comment]
> > > > Suggestion. Can you recreate the crash with MoroKernel for Q
> > > > Download : https://androidfilehost.com/?fid=4349826312261770822
> > > > Please let me know,
> > > 
> > > 
> > > Still crashes
> > > [log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4519989/log_kmsg.log)
> > 
> > 
> > Thank you for testing, this saved me alot of time.
> > After multiple logs, this `vfsspi_fp_homekey_ev : not set the retain pin!` seems to be occuring every single time before the the device is hard reseted.
> > while i investigate this further. could you please try to disable Adaptive fast charging in settings (you can do so by long pressing the "fast charging" in notification bar)
> > if you have done that already do let me know.
> > edit : when you hard reset do you press voldown + power still or voldown + power + home
> > Thanks,
> 
> I disabled fast charging and so far so good. The phone is in full charge for two hours now. I will let you know later if something changes.
> 
> As for the combination, I press voldown + power + home. Never can remember which combination works :p

Ok this is some good news at last, i had doubts it is AFC (Adaptive Fast Charge) but really was not sure (i dont use AFC that might explain why i never ran into it)

i hope you can continue testing without AFC.

regarding hard reset, please only do VOL DOWN + POWER (it works).

this avoids extra spam while logging.

Thank you alot for testing! much appreciated

**Comment by fz75** [comment]
When I had to restart the phone, I managed to do it, only by restarting in donload mode! Now I'm doing a test, deactivating AOD, let's see what happens !!!

**Comment by freakbox69** [comment]
> > Suggestion. Can you recreate the crash with MoroKernel for Q
> > Download : https://androidfilehost.com/?fid=4349826312261770822
> > Please let me know,
> 
> Still crashes
> 
> [log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4519989/log_kmsg.log)

 

> Suggestion. Can you recreate the crash with MoroKernel for Q
> 
> Download : https://androidfilehost.com/?fid=4349826312261770822
> 
> Please let me know,

Did not crash this morning, installed moroKernal for Q as suggested yesterday.

**Comment by johnybr99** [comment]
I tried leaving AFC on tonight but with constant aod as someone previously suggestwd. The results vere identical.

**Comment by fz75** [comment]
I did the test, to put it in charge with AOD off, fast charge disabled, at 2.00 am and this morning at 6.00 am the phone was blocked!  To restart it, I had to restart it in download mode!  It didn't work, not even in recovery mode.  I just can't understand what the cause may be!

**Comment by ananjaser1211** [comment]
So AFC does not matter but AOD keeps it working ?

Interesting

This means that when the phone enters doze and charging at the and time something wrong happens.

**Comment by johnybr99** [comment]
> So AFC does not matter but AOD keeps it working ?
> 
> Interesting
> 
> This means that when the phone enters doze and charging at the and time something wrong happens.

AOD doesn't matter as well.

**Comment by fz75** [comment]
Charged, this morning, with wireless charger, airplane mode, active AOD, taken after about 3 hours, phone ok, no problem!

**Comment by johnybr99** [comment]
> Charged, this morning, with wireless charger, airplane mode, active AOD, taken after about 3 hours, phone ok, no problem!

It is enitrely possible to charge the phone completely, sometimes it will even go hours beyond that (my record is 4+ hours), but it will eventually hang if you leave it on the charger, though the time it takes to hang is really random.

**Comment by fz75** [comment]
Last night, put in charge, with wireless charger, quick charge off, AOD, always on, this morning no problem!  The only oddity, which I noticed is that when I unlocked it with the fingerprint, it asked me for the Pin, as happens when I restart the phone!  As if during the night, during the charge, he restarted alone!

**Comment by johnybr99** [comment]
Last night I tried AFC with Store mode on, meaning the phone would stop charging at 100%, but it didn't do much as I found my phone frozen in the morning. I turned it on, disabled AFC and left it on a charger for another 3 hours. It didn't freeze. All of this was done with AOD set to always on.

**Comment by Skyterix1991** [comment]
No AOD and no fast charging crashed.

[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4533840/log_kmsg.log)

**Comment by youmoLC** [comment]
Maybe the effective way is to get the phone to restore the factory settings at a time.
I think the problem is the Android setup wizard.

**Comment by ananjaser1211** [comment]
i have left my phone overnight in fast charger (so far 12 hours) and it has not yet crashed.
the difference is i enabled the screen saver (settings > display > screen saver > colors)

so the phone shows up colors while charging, it has not yet crashed so im pretty sure that when the phone fully dozes the crash happens

**Comment by PandamonidorRX** [comment]
> deixei meu telefone durante a noite no carregador rápido (até 12 horas) e ele ainda não caiu.
> a diferença é que eu ativei o protetor de tela (configurações> tela> protetor de tela> cores)
> 
> para que o telefone mostre cores durante o carregamento, ele ainda não travou, por isso tenho certeza de que, quando o telefone cochilar completamente, o travamento acontece

there is no way to disable the sleep that causes the failures? or use another way of sleeping?

**Comment by youmoLC** [comment]
The crash is characteristic.
1.When the phone restarts for the first time, it is easy to crash without Google verification success.
2.When the phone crashes, We can enter the settings through the status bar.
So it is highly likely that the wrong application is the "SetupWizard v229.271733002".Although it has no errors in itself, it prevents us from entering the system UI.

**Comment by matinzd** [comment]
> i have left my phone overnight in fast charger (so far 12 hours) and it has not yet crashed.
> the difference is i enabled the screen saver (settings > display > screen saver > colors)
> 
> so the phone shows up colors while charging, it has not yet crashed so im pretty sure that when the phone fully dozes the crash happens

Yeah thats true. I may provide logs for you either.

**Comment by matinzd** [comment]
> > > Suggestion. Can you recreate the crash with MoroKernel for Q
> > > Download : https://androidfilehost.com/?fid=4349826312261770822
> > > Please let me know,
> > 
> > 
> > Still crashes
> > [log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4519989/log_kmsg.log)
> 
> Thank you for testing, this saved me alot of time.
> 
> After multiple logs, this `vfsspi_fp_homekey_ev : not set the retain pin!` seems to be occuring every single time before the the device is hard reseted.
> 
> while i investigate this further. could you please try to disable Adaptive fast charging in settings (you can do so by long pressing the "fast charging" in notification bar)
> if you have done that already do let me know.
> 
> edit : when you hard reset do you press voldown + power still or voldown + power + home
> 
> Thanks,

I cannot find adaptive fast charging option ^_^

**Comment by ananjaser1211** [comment]
Please try the new kernel : [Here](https://github.com/ananjaser1211/Cronos_8890/releases/tag/V3.5)

It might take few cycles for the effects to take in place. Thanks

**Comment by matinzd** [comment]
> Please try the new kernel : [Here](https://github.com/ananjaser1211/Cronos_8890/releases/tag/V3.5)
> 
> It might take few cycles for the effects to take in place. Thanks

I can confirm that this bug is fixed in cronos kernel v3.5

**Comment by ananjaser1211** [comment]
Still waiting for more reports because the bug happens randomly

**Comment by Skyterix1991** [comment]
Crashed too.

[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_8890/files/4558237/log_kmsg.log)

**Comment by ananjaser1211** [comment]
Alright, so now we conclude its not a kernel issue.

i will look into the ROM and see if i can figure what is causing it.

Thanks guys

**Comment by JeffS2Duda** [comment]
In the previous kernel, my phone crashed two nights in a row.  I kept the same conditions as before, I didn't change any configuration and just updated the kernel and it didn't crash tonight.

**Comment by kukuhajip** [comment]
After install new kernel, i try activated quick charge, this issue still happen. Teach me how to get the log, maybe it can help develop further... thank..

**Comment by JeffS2Duda** [comment]
My phone still has fast charging active and so far it hasn't crashed

**Comment by kukuhajip** [comment]
Maybe crashed happen, when charging for long time period (over (x) hours). I, charge from 9 PM until 6 am.. tonight I will try turn off fast charging.. see what happen next..

**Comment by ananjaser1211** [comment]
Id love if someone could figure out some pattern, AFC on/off does not matter
some users got the crash while using AOD while the majority did not

my device is using fast charger, no aod, no screen saver. and it has yet to crash. i leave it charging for well over 12 hours, sometimes over a full day (as it is not my main phone)

so i still cant see one single pattern. 

The ONLY thing of relevancy i see is in regards to battery % . When the rom is first installed most users are going to get this bug 90% of the time for couple nights, which makes me think that when the battery % in the rom reports 100%. it is not really correct (you can see this by going to offline charging and notice a difference in percentage)

So with the wrong system %, the kernel continues on charging, phones goes 101% (which is actually 98% or such) ? and crashes because what the fuck lol.

idk, it is just a theory, there is a correlation between battery % and charging and this bug im 100% sure. because leaving the phone to charge for 2 hours will not crash it, leaving it in the charger for 2 more hours on affected devices will.

**For those who face it very regularly (like every night), on the new kernel, if possible do a recalibration and run the phone through 2 or more cycles.**

and from there we see if there is anything to observe. removal of custom kernel mods did seem to help reduce the count of this issue (since there are few people in our group and those who reached out in PM claim it "fixed" the issue, when in fact it did not really) but the frequency of it might have went down. 

but i bet this was due to people % getting "calibrated" more than actual kernel changes

**Comment by johnybr99** [comment]
When I was using BD Pie roms, my percentage in TWRP was always lower than the percentage in system. Also, once I reached about 90% in system, it would do a rapid charge to 100%, I would get those remaining 10% in like 25 secs. That doesn't happen in Q, that's the only observable difference I can notice.

**Comment by ananjaser1211** [comment]
> EDIT: I just noticed that reported offline percentage is 66%, whilst system's percentage is 74%.

That is the issue im after right now, not the TWRP charging percent, that one can be different it happens (due to twrp using oreo kernel drivers while system is using pie)

However the one in question is the offline charging percentage. if possible let it charge to a 100% there and see if the overnight crash happens agian

**Comment by takmobile** [comment]
Hello.
There is no way to solve this problem yet ??
I would love to see this resolved.

**Comment by ananjaser1211** [comment]
@takmobile Read the last few posts as they give info on why I think this issue exists and how to mitigate it

**Comment by takmobile** [comment]
I don't think it has anything to do with charging or AOD.
This problem occurs every 2 to 3 hours when the device is idle

**Comment by ananjaser1211** [comment]
> I don't think it has anything to do with charging or AOD.
> This problem occurs every 2 to 3 hours when the device is idle

Any details on why you think that ? When i was testing idle drain a while back my phone would have runtimes of over 7 days with most of it being idle. it never crashed once.

**Comment by Skyterix1991** [comment]
> > I don't think it has anything to do with charging or AOD.
> > This problem occurs every 2 to 3 hours when the device is idle
> 
> Any details on why you think that ? When i was testing idle drain a while back my phone would have runtimes of over 7 days with most of it being idle. it never crashed once.

There is no problem with the device being idle. I have successfully used it for days with no problem except charging. It crashes every time I leave it still plugged in when a charge is at 100%. It takes a while (about 1-3 hours) and then crashes.

**Comment by SpikeJr** [comment]
Something I'm noticing is, every night after the full charge, the phone have a restart (I know it for the message when I try to unlock the phone)
I have the AOD active, preventing the crash, but causing a restart (the phone keeps working normally)
Maybe the bug it's caused by that restart?

**Comment by JeffS2Duda** [comment]
I'm keeping my cell phone with Always On Display and Fast Charge enabled and I've already kept the cell phone charging for almost 12 hours without touching it, so far it hasn't stopped.

**Comment by johnybr99** [comment]
> > EDIT: I just noticed that reported offline percentage is 66%, whilst system's percentage is 74%.
> 
> That is the issue im after right now, not the TWRP charging percent, that one can be different it happens (due to twrp using oreo kernel drivers while system is using pie)
> 
> However the one in question is the offline charging percentage. if possible let it charge to a 100% there and see if the overnight crash happens agian

This last paragraph has solved my overnight crashing issue, for now. I charged my phone to a 100%, then turned it off with it plugged in. It showed around 95%. Then I charged it to a 100% without turning it on (offline charging). When I turned it on, and turned it back off, it was at around 96%. I did that multiple tines until it showed 99% when I turned my phone off for offline charging. I did that 2 days ago and haven't had any crash since.

**Comment by ananjaser1211** [comment]
> i did that multiple tines until it showed 99% when I turned my phone off for offline charging. I did that 2 days ago and haven't had any crash since.

Hope everyone here can do the same. if this is indeed the crash cause, atleast we have a proper workaround until i somehow figure out what the fuck Q does differently that makes charging % useless

**Comment by kukuhajip** [comment]
offline charging = turn off the phone? I try turn off the phone and plug in charger, then the phone on and not restart (no need patern after restart)

**Comment by ananjaser1211** [comment]
> offline charging = turn off the phone? I try turn off the phone and plug in charger, then the phone on and not restart (no need patern after restart)

Yes. letting the phone charge while its powered off, to top-off the last % 

cuz the rom thinks it has 100% when it does not really.

**Comment by gorandroid** [comment]
I have similar problem, the phone just crashes randomly, goes black screen... when doing any things it just turns off and won't turn on if i don't put it to charger then it turns on normally, so if i plug it in the charger it can turn on after the crash... wtf?

**Comment by Switchof** [comment]
> Id love if someone could figure out some pattern, AFC on/off does not matter
> some users got the crash while using AOD while the majority did not
> 
> my device is using fast charger, no aod, no screen saver. and it has yet to crash. i leave it charging for well over 12 hours, sometimes over a full day (as it is not my main phone)
> 
> so i still cant see one single pattern.
> 
> The ONLY thing of relevancy i see is in regards to battery % . When the rom is first installed most users are going to get this bug 90% of the time for couple nights, which makes me think that when the battery % in the rom reports 100%. it is not really correct (you can see this by going to offline charging and notice a difference in percentage)
> 
> So with the wrong system %, the kernel continues on charging, phones goes 101% (which is actually 98% or such) ? and crashes because what the fuck lol.
> 
> idk, it is just a theory, there is a correlation between battery % and charging and this bug im 100% sure. because leaving the phone to charge for 2 hours will not crash it, leaving it in the charger for 2 more hours on affected devices will.
> 
> **For those who face it very regularly (like every night), on the new kernel, if possible do a recalibration and run the phone through 2 or more cycles.**
> 
> and from there we see if there is anything to observe. removal of custom kernel mods did seem to help reduce the count of this issue (since there are few people in our group and those who reached out in PM claim it "fixed" the issue, when in fact it did not really) but the frequency of it might have went down.
> 
> but i bet this was due to people % getting "calibrated" more than actual kernel changes
> 
> **EDIT : Also just now i noticed my phone finally reports 100% in offline charging + 100% in the ROM. this could be why i am not getting that crash at all. i just charge my phone to 100% through offline charging once and it seems to stick i think**

The charging issue is vary and it is the major thing that causes a lot of issues.Sometimes when charging it's keep discharging the device even whn not in use but aod turned on.The % drop itself in charging.I have tried the solution : 
>
> offline charge % = online charging % but it is later goes lesser again for offline charge after a few cycle
>
When checking current measurement in ampere for charging (both with / without fast charging) the charge is unstable.Sometime it's stay at 0mA and a msg (screenshot attached) pop up.Even if accept it for old measurement method also doesn't make any change!

![Screenshot_20200505-172135_Ampere](https://user-images.githubusercontent.com/64365899/81062235-36325500-8f08-11ea-9832-6cbd62e8ba76.jpg)

**Comment by johnybr99** [comment]
Last night it froze after 5 days of not doing that. Difference now being that I turned the phone facing the ground, so AOD turned itself off.

**Comment by Skyterix1991** [comment]
I have some news. I calibrated a battery and today was the first night that phone hasn't crashed.
Maybe I just got lucky, I will let you know later but it seems promising.

Followed this guide (Method 1): https://forum.xda-developers.com/android/general/guide-how-to-callibrate-battery-device-t3308554

**Comment by Skyterix1991** [comment]
Second night still no crash.

**Comment by qstar-inc** [comment]
Hello everyone, I've following this thread for some time now. I still haven't installed FloydQ yet since it still doesn't have one of the crucial feature I need, but I'm following the development. Anyways, the reason I wanted to give some input is because I have somewhat similar issues.

ROM: BlackDiamond N8 PIE v8 (clean installed with v7, then updated to v8 later)
Kernel: Cronos v3.0 (used Moro 8.1 and Jack O'Neill as well)

My experience related to this thread happened yesterday and the day before yesterday. Never before flashing Cronos.

- Experience 1: Phone was on charge, using non Fast Charging cable. AOD & Fast Charging was on. After a while AOD disappeared, phone got hotter, I assume it was a while after it reached 100%. I force rebooted and everything went fine.

- Experience 2: Phone was on idle, AOD on. Last time I used was at around 8:20PM. Then I put it on desk. No one else touched it. At 8:39PM I looked at the AOD and it was stuck at around 8:32PM. Again, had to force reboot.

This might not be helpful at all. I also don't know if there's any connection between these scenarios. But I was just hoping if it might help the development.
Anyways, good luck and hope everything goes well.

**Comment by ananjaser1211** [comment]
Wait... The issue happened on Pie too ?? But that does not make sense.
No one ever reported it before. and the issue happens on cronos , moro and jack too ?
(all 3 kernels with different ways to handle battery)

This is puzzling again

**Comment by johnybr99** [comment]
> Wait... The issue happened on Pie too ?? But that does not make sense.
> No one ever reported it before. and the issue happens on cronos , moro and jack too ?
> (all 3 kernels with different ways to handle battery)
> 
> This is puzzling again

The issue he's having is not the same as overnight crash. Something else is at play there, probably some kind of hardware failure.

**Comment by ananjaser1211** [comment]
@johnybr99 Hopefully its not.. i can barley focus enough on Q alone trying to fix it, if it occurs in Pie aswell its a whole other mess now

**Comment by qstar-inc** [comment]
@ananjaser1211 it happened only on Cronos, not on Moro or Jack.

**Comment by mathy007** [comment]
@qstar-inc It still crashed on moro BTW there's no jack for Floyd if am not mistaken,so there's something wrong elsewhere

**Comment by Skyterix1991** [comment]
> I have some news. I calibrated a battery and today was the first night that phone hasn't crashed.
> Maybe I just got lucky, I will let you know later but it seems promising.
> 
> Followed this guide (Method 1): https://forum.xda-developers.com/android/general/guide-how-to-callibrate-battery-device-t3308554

So it crashed. Still unnerving that it decided not to crash the first two nights for no apparent reason,

**Comment by johnybr99** [comment]
> > I have some news. I calibrated a battery and today was the first night that phone hasn't crashed.
> > Maybe I just got lucky, I will let you know later but it seems promising.
> > Followed this guide (Method 1): https://forum.xda-developers.com/android/general/guide-how-to-callibrate-battery-device-t3308554
> 
> So it crashed. Still unnerving that it decided not to crash the first two nights for no apparent reason,

Did you have AOD on? Also, if you have AOD on and turn your phone facing the ground, it will turn itself off and freeze after a while.

**Comment by SpikeJr** [comment]
I have a question
This happens at any time, or only when charges to 100%?
If the case is that it happens when on 100%, maybe a Power Input controller will be helpful?
Like the Input Power Control module from Magisk, or the Advanced Charging Controller
It's just a theory

**Comment by Skyterix1991** [comment]
> > > I have some news. I calibrated a battery and today was the first night that phone hasn't crashed.
> > > Maybe I just got lucky, I will let you know later but it seems promising.
> > > Followed this guide (Method 1): https://forum.xda-developers.com/android/general/guide-how-to-callibrate-battery-device-t3308554
> > 
> > 
> > So it crashed. Still unnerving that it decided not to crash the first two nights for no apparent reason,
> 
> Did you have AOD on? Also, if you have AOD on and turn your phone facing the ground, it will turn itself off and freeze after a while.

I didn't have an AOD on. But I can't remember which way my phone was facing.

**Comment by johnybr99** [comment]
> > > > I have some news. I calibrated a battery and today was the first night that phone hasn't crashed.
> > > > Maybe I just got lucky, I will let you know later but it seems promising.
> > > > Followed this guide (Method 1): https://forum.xda-developers.com/android/general/guide-how-to-callibrate-battery-device-t3308554
> > > 
> > > 
> > > So it crashed. Still unnerving that it decided not to crash the first two nights for no apparent reason,
> > 
> > 
> > Did you have AOD on? Also, if you have AOD on and turn your phone facing the ground, it will turn itself off and freeze after a while.
> 
> I didn't have an AOD on. But I can't remember which way my phone was facing.

Try having aod on overnight at least, make sure your phone is facing up. It should stop crashing. It's not a fix, but a temporary workaround I found that works for me.

**Comment by SpikeJr** [comment]
> > > > > I have some news. I calibrated a battery and today was the first night that phone hasn't crashed.
> > > > > Maybe I just got lucky, I will let you know later but it seems promising.
> > > > > Followed this guide (Method 1): https://forum.xda-developers.com/android/general/guide-how-to-callibrate-battery-device-t3308554
> > > > 
> > > > 
> > > > So it crashed. Still unnerving that it decided not to crash the first two nights for no apparent reason,
> > > 
> > > 
> > > Did you have AOD on? Also, if you have AOD on and turn your phone facing the ground, it will turn itself off and freeze after a while.
> > 
> > 
> > I didn't have an AOD on. But I can't remember which way my phone was facing.
> 
> Try having aod on overnight at least, make sure your phone is facing up. It should stop crashing. It's not a fix, but a temporary workaround I found that works for me.

His intention was to try to solve the problem. The temporary workaround it's, well, temporary...

**Comment by JeffS2Duda** [comment]
Since I updated my Kernel to version 3.5, it has not crashed anymore.  I left it all night charging with the screen facing down and it also didn't crash.  I leave it turned upside down some nights too.  I'm using AOD and Fast Charge.

**Comment by SpikeJr** [comment]
(I write this to help with diagnosing the problem, not for trying to solve a problem that I caused)
A few moments ago I wanted to try a new turbo charger I've recently got. Just for curiosity, I activate the fast charge
Until then, the phone doesn't charge anymore, even turning off the fast charge in settings. I'm typing this text while I'm connected to the charger. I've tried a normal charger too, and I have the same results
It's curious how the ROM handle the charging. I imagine that the problem residues there, and not in a doze moment (if that were the case, this bug will even pop up?)
I'll try to fix this, but until then, hopefully this is useful for information
(Screenshot of the "charging" information below (
![Screenshot_20200509-014151_Ampere](https://user-images.githubusercontent.com/64614720/81464368-7824fa80-9197-11ea-9271-a412a8f76a49.jpg)

**Comment by qstar-inc** [comment]
> 
> 
> @qstar-inc It still crashed on moro BTW there's no jack for Floyd if am not mistaken,so there's something wrong elsewhere

Pie, I was saying it happened on Pie.

**Comment by floviolleau** [comment]
Hi,

Thanks a lot for your amazing job here and all efforts! 👍 

On my SM-G935F (S7 Edge France), I have the exact same issue.

I read carefully this thread to be able to pay attention for the very first night with this rom and try to help to solve the issue with my investigations.

So, I deactivated all battery/app optimisations, do normal charge with an official charger (no fast charge, no wireless charge).

I activated AOD during a range of time (00:30 to 10:00am).

This night I woke up shortly at 5:00 am and I checked the phone :). 100%, green light, AOD still active and I was able to unlock the phone and check few things. I let the phone plugged to the charger. Then I go back to sleep...

When I woke up later (after 10:00 am), AOD was deactivated, the phone still on the charger, green light and impossible to unlock it or turn on the screen. I was forced to volume down + power to hard reboot.

What kind of other help can I do?

Kind regards

**Comment by honda0** [comment]
hey i installed moro kernel  now it won't  crash over night

**Comment by honda0** [comment]
and the audio fixed now its working wityout go silent

**Comment by PandamonidorRX** [comment]
> ei, eu instalei o kernel moro agora ele não falha durante a noite

does it really work?

**Comment by PandamonidorRX** [comment]
> hey i installed moro kernel now it won't crash over night

does it really work?

**Comment by mathy007** [comment]
@PandamonidorRX Am currently using moro and still getting the crash, no worries though fix will definitely come

**Comment by PandamonidorRX** [comment]
I understand, I would like it to work soon, I'm in oreo with Moro kernel 8.1, waiting fix the bugs

**Comment by ananjaser1211** [comment]
Few updates about this issue and many others

https://forum.xda-developers.com/showpost.php?p=82535375&postcount=466

**Comment by honda0** [comment]
> > hey i installed moro kernel now it won't crash over night
> 
> does it really work?

2 days for now no problems

**Comment by ananjaser1211** [comment]
So, i FINALLY managed to make my phone crash overnight!

My battery offline was 100% when i left it to charge (system was 100%) , i turned off AOD, screen saver and anything that can turn on the phone, and i clean flashed.

And to my surprise, The phone is actually alive when it is in "overnight bug" state!

I have managed to pull critical system logs live from the device while it was stuck at the overnight state, i will be spending probably the entire week reading them trying to figure out what went wrong. But here is what so far i understand

1) charging mode does not matter.
2) % Mismatch does not matter
3) Power management does not matter

The only variable that matters is whether the phone enters doze or not, which can be affected by notifications , AOD, screen saver and many more.

How the phone crashes :-

The crash is a 2 Step process. it is not just the phone going blank as i supposed.

1) At some point, the Phone Reboots (Due to all services dying)
2) The phone starts booting. 
- In some cases it boots up (why some users reported that they found their phone rebooted and it asked for pin)
- However in some other cases, we get the device stuck at black screen with green LED
3) When the phone crashes in step 1, it happens some point after dalvik is loaded and then we get 

`05-11 05:09:42.759  3978  4133 E Watchdog: !@Sync 55 [2020-05-11 05:09:42.759] FD count : 609, wdog_way : softdog
05-11 05:09:42.760  3978  4133 E Watchdog_N: !@Failed to ioctl to /dev/watchdog1 // errno : 25`

And then stuff start dying, it is a soft crash, therefore the phone does not kernel panic or reboots. I hope the watchdog dump is stored somewhere. will update when i find more info


[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4608403/log_e.log)
[log_dmesg.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4608402/log_dmesg.log)
[log_v.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4608397/log_v.log)
[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4608395/log_kmsg.log)

**Comment by PandamonidorRX** [comment]
and what's next for now? just wait ? or already have something ready? Sorry for my bad english

**Comment by ananjaser1211** [comment]
> and what's next for now? just wait ? or already have something ready? Sorry for my bad english

“i will be spending probably the entire week reading them trying to figure out what went wrong”

**Comment by PandamonidorRX** [comment]
Thanks <3

**Comment by Switchof** [comment]
> > and what's next for now? just wait ? or already have something ready? Sorry for my bad english
> 
> “i will be spending probably the entire week reading them trying to figure out what went wrong”

Anan i found out turning off bluetooth scanning (Location>Improve accurancy>Bluetooth scanning) stopped phone crashing overnight.So far i didn't face any crash about 1 weeks with fast charging and aod turned on.lm on cronos 3.5 with all fixes applied.Hope this help u to dig further about the issue.Unfortunately mismatch % (online/offline) still exist.
![Screenshot_20200514-231524_Settings](https://user-images.githubusercontent.com/64365899/81953864-c411ec80-963a-11ea-9ba9-66b7ae3ffc73.jpg)

**Comment by johnybr99** [comment]
> > > and what's next for now? just wait ? or already have something ready? Sorry for my bad english
> > 
> > 
> > “i will be spending probably the entire week reading them trying to figure out what went wrong”
> 
> Anan i found out turning off bluetooth scanning (Location>Improve accurancy>Bluetooth scanning) stopped phone crashing overnight.So far i didn't face any crash about 1 weeks with fast charging and aod turned on.lm on cronos 3.5 with all fixes applied.Hope this help u to dig further about the issue.Unfortunately mismatch % (online/offline) still exist.
> ![Screenshot_20200514-231524_Settings](https://user-images.githubusercontent.com/64365899/81953864-c411ec80-963a-11ea-9ba9-66b7ae3ffc73.jpg)

I don't think that bt scanning has anything to do with this. I have it on and when my AOD is on during night, it doesn't crash. If I put my phone facing down, meaning aod automatically turns itself off, it crashes. Try that.

**Comment by Switchof** [comment]
> > > > and what's next for now? just wait ? or already have something ready? Sorry for my bad english
> > > 
> > > 
> > > “i will be spending probably the entire week reading them trying to figure out what went wrong”
> > 
> > 
> > Anan i found out turning off bluetooth scanning (Location>Improve accurancy>Bluetooth scanning) stopped phone crashing overnight.So far i didn't face any crash about 1 weeks with fast charging and aod turned on.lm on cronos 3.5 with all fixes applied.Hope this help u to dig further about the issue.Unfortunately mismatch % (online/offline) still exist.
> > ![Screenshot_20200514-231524_Settings](https://user-images.githubusercontent.com/64365899/81953864-c411ec80-963a-11ea-9ba9-66b7ae3ffc73.jpg)
> 
> I don't think that bt scanning has anything to do with this. I have it on and when my AOD is on during night, it doesn't crash. If I put my phone facing down, meaning aod automatically turns itself off, it crashes. Try that.

Then i try a few cycle with aod turned off

**Comment by floviolleau** [comment]
I've got the same issue from time to time on a samsung S7 Edge under LOS 17.1 (SM-G935F). Overnight charge and on the morning, the phone is blocked (green light screen blocked) and the morning alarm do not work.

**Comment by Switchof** [comment]
> > > > > and what's next for now? just wait ? or already have something ready? Sorry for my bad english
> > > > 
> > > > 
> > > > “i will be spending probably the entire week reading them trying to figure out what went wrong”
> > > 
> > > 
> > > Anan i found out turning off bluetooth scanning (Location>Improve accurancy>Bluetooth scanning) stopped phone crashing overnight.So far i didn't face any crash about 1 weeks with fast charging and aod turned on.lm on cronos 3.5 with all fixes applied.Hope this help u to dig further about the issue.Unfortunately mismatch % (online/offline) still exist.
> > > ![Screenshot_20200514-231524_Settings](https://user-images.githubusercontent.com/64365899/81953864-c411ec80-963a-11ea-9ba9-66b7ae3ffc73.jpg)
> > 
> > 
> > I don't think that bt scanning has anything to do with this. I have it on and when my AOD is on during night, it doesn't crash. If I put my phone facing down, meaning aod automatically turns itself off, it crashes. Try that.
> 
> Then i try a few cycle with aod turned off

I didn't get any crash during 2 cycles with aod turned off.Later i test 1 cycle with bt scanning on also no crash.Somehow im not getting crash again with fast charging on.

**Comment by SpikeJr** [comment]
> (I write this to help with diagnosing the problem, not for trying to solve a problem that I caused)
> A few moments ago I wanted to try a new turbo charger I've recently got. Just for curiosity, I activate the fast charge
> Until then, the phone doesn't charge anymore, even turning off the fast charge in settings. I'm typing this text while I'm connected to the charger. I've tried a normal charger too, and I have the same results
> It's curious how the ROM handle the charging. I imagine that the problem residues there, and not in a doze moment (if that were the case, this bug will even pop up?)
> I'll try to fix this, but until then, hopefully this is useful for information
> (Screenshot of the "charging" information below (
> ![Screenshot_20200509-014151_Ampere](https://user-images.githubusercontent.com/64614720/81464368-7824fa80-9197-11ea-9271-a412a8f76a49.jpg)

So, my phone didn't charge anymore.
I don't know if was a physical problem or a power management problem, and I do wanna know if was one or another, to know if I'm able to use Turbo Charge

Anybody can confirm what was the problem? (Or if this deserves another thread and not in here)

The steps to the bug are in the quoted message
(Fortunately, the warranty it's repairing the phone. It seem like the micro USB plug was damaged)

**Comment by omidsa596** [comment]
Mine too.and overheating badly
Thank you dev.

**Comment by zweisora** [comment]
Hi @ananjaser1211 

I didn't get this bug after removing 
"pm.sleep_mode=1" from build.prob
In my case, With aod on/off or and fast charging on/off this issue solved.

Maybe the others can try too, and see if the problem solved or not.

My phone : G930F/FD
I hope this information can help you.

Thank you

**Comment by omidsa596** [comment]
I check. Thanks for everything Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: zweisora <notifications@github.com> Date: 01/06/2020  05:47  (GMT+03:30) To: ananjaser1211/FloydQ_Reports <FloydQ_Reports@noreply.github.com> Cc: omidsa596 <omidsa596@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [ananjaser1211/FloydQ_Reports] [BUG] Phone crashed overnight (#7) 
Hi @ananjaser1211
I didn't get this bug after removing
"pm.sleep_mode=1" from build.prob
In my case, With aod on/off or and fast charging on/off this issue solved.
Maybe the others can try too, and see if the problem solved or not.
My phone : G930F/FD
I hope this information can help you.
Thank you

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ananjaser1211/FloydQ_Reports/issues/7#issuecomment-636564891",
"url": "https://github.com/ananjaser1211/FloydQ_Reports/issues/7#issuecomment-636564891",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by omidsa596** [comment]
Hi.i install again.  pm.sleep in biuld.prob deleted. But drain battery very fast and over hit in my phone. Any solution?  ThanksSent from my Samsung Galaxy smartphone.
null

**Comment by bhavin08rockstar** [comment]
Even i had the same issue last night, i have attached my log file too.
[log_kmsg.log](https://github.com/ananjaser1211/FloydQ_Reports/files/4731319/log_kmsg.log)

**Comment by teualin** [comment]
I don't have any logs and i haven't used this rom yet.

From what i can remember i had a similar issue on the pie ported roms. 
What would happen is that i would leave my phone to charge and when i came back to it, the phone would be frozen with a black screen and the green notification light on. A reboot would bring things back to normal.

This happened to several pie roms. I thought this piece of information might help.

My phone is G930F.

**Comment by rock6663** [comment]
When phone charge reaches full it didnt changed notification led to green it stayed as red the problem is aod said it was fully charged then i realised it turns green after crash maybe this will help to you (also i tried to grab it before crash led turned to green and it didnt crashed)

**Comment by ananjaser1211** [comment]
> When phone charge reaches full it didnt changed notification led to green it stuck as red the problem is aod said it was fully charged then i realised it turns green after crash maybe this will help to you (also i tried to grab it before crash led turned to green and it didnt crashed) @ananjaser1211

Good point, at 100% the LED status remains red for a while, on my phone it takes around 10 minutes..

ill take a look at the LED driver. it does not crash for me still even when its green. but it does take time to switch

**Comment by LaLeLu68** [comment]
I play around Magisk and use the ACC module.
Since i do this my phone wont freeze in the morning. 

I changed the recharge circle to 90%. So the phone will begin to charge at 90%. 

Steps: 
Install ACC in Magisk Manager
after install and reboot do this :

1. open Terminal
2. type "acc"
3. select option "b"
4. select option "a"
5. select option "7" to charge 100%
6. select option "e"
7. let the termin open
8. charging to 100%
9. type "acc -d 90%"
10. dont close the terminal

**Comment by rock6663** [comment]
@ananjaser1211 my phone crashed while i was talking with my friend it was not pluged into charging i will send logs if i can

**Comment by ananjaser1211** [comment]
> @ananjaser1211 my phone crashed while i was talking with my friend it was not pluged into charging i will send logs if i can

hope you saved /proc/last_kmsg , data/log and data/tombstones before they get overwritten.

i would bet i am never going to be able to re-create this crash already.

**Comment by rock6663** [comment]
> > @ananjaser1211 my phone crashed while i was talking with my friend it was not pluged into charging i will send logs if i can
> 
> hope you saved /proc/last_kmsg , data/log and data/tombstones before they get overwritten.
> 
> i would bet i am never going to be able to re-create this crash already.

I got last_kmsg and data/log but tombstones was empty i will upload them to drive and send it to you

**Comment by Switchof** [comment]
@ananjaser1211 on v2 with cronos 4.5 or 4.0 battery offline and online measurements not same even tried charge offline to 100% somehow next cycle it still lesser again in offline.Like this it goes 100% - 90% very fast.Just to make sure this with other kernel i tried moro and the offline and online measurement are same even after a few cycles.But moro kernel not well adapt with the rom like cronos did.The overnight bug also not visible in moro but this cannot be confirmed because in cronos also is not happen frequently.My question is how could battery reading is not same in offline and online when it suppose to read from same source.Do this could be a reason of this bug too?

**Comment by Switchof** [comment]
I pull this logs live from the device while it was stuck at the overnight state from V2 with cronos 4.5 (Phone freeze with a black screen and the green notification light on)

[Logs.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4873552/Logs.zip)

**Comment by arkgnan** [comment]
> @ananjaser1211 on v2 with cronos 4.5 or 4.0 battery offline and online measurements not same even tried charge offline to 100% somehow next cycle it still lesser again in offline.Like this it goes 100% - 90% very fast.Just to make sure this with other kernel i tried moro and the offline and online measurement are same even after a few cycles.But moro kernel not well adapt with the rom like cronos did.The overnight bug also not visible in moro but this cannot be confirmed because in cronos also is not happen frequently.My question is how could battery reading is not same in offline and online when it suppose to read from same source/path.Do this could be a reason of this bug too?

That is happen to me after calibrate the battery with *#0228# method. I don't know it is an issue or not, should we open new report as [BUG]?

**Comment by souzajerry** [comment]
in v3 with cronos 5.0 and moro kernel v8.4 I didn't get any problems, however I always have the AOD on while I charge the phone

**Comment by ananjaser1211** [comment]
I think i am going to change this to patched/wontfix.

i have added alot of changes in V4 to handle this, along side the fixes in V3 it either eliminates the issue completely (in my case and few testers) or it crashes once or twice in the first day/3days and then the issue is completely gone. 

so i dont think there is any further fixes that are possible for this bug. besides avoid reflashing to a different ROM every single day, and if you want to use Q. let the phone settle for few days, the issue will remove itself.

**Comment by mathy007** [comment]
@ananjaser1211 I'd say mark this issue as fixed as it doesn't happen on latest build

**Comment by arkgnan** [comment]
> I think i am going to change this to patched/wontfix.
> 
> i have added alot of changes in V4 to handle this, along side the fixes in V3 it either eliminates the issue completely (in my case and few testers) or it crashes once or twice in the first day/3days and then the issue is completely gone.
> 
> so i dont think there is any further fixes that are possible for this bug. besides avoid reflashing to a different ROM every single day, and if you want to use Q. let the phone settle for few days, the issue will remove itself.

Wow v4 will be released soon, is it in the near future or is it still long?

**Comment by SypeR54** [comment]
@arkgnan Anan still working on the new version to make it more compatible. But the final version released after Samsung releases a August patch for S9+ firmware. But in short, yes its possible to see V4 in a month later (if we didn't had any another major bug).

**Comment by arkgnan** [comment]
> @ananjaser1211 I'd say mark this issue as fixed as it doesn't happen on latest build

does this issue still occur in v4.0 ?

**Comment by SypeR54** [comment]
@arkgnan Yesterday i had for the first tine overnight crash but i believe its caused from lots of dirty flash. Otherwise, i didn't happen same thing

**Comment by Gutech1** [comment]
Was the problem fixed in v4.0?

**Comment by ananjaser1211** [comment]
I have marked this now as unconfirmed. While testing V5 (both dirty and clean installations) not a single tester faced the overnight crash. so this might have been resolved, or our tester base is not large enough (we have ~30 active testers right now)

i will keep this open and wait for reports from you guys when V5 is released

**Comment by ananjaser1211** [comment]
Hey everyone, can anyone here tell me if they have faced the overnight crash under V5 ?

**Comment by ananjaser1211** [comment]
I have ran a poll on our group. the majority stopped facing this bug in V5, therefore i can finally mark this as solved. while its not a 100% concrete evidence that this bug is gone, the votes came from an active group where ive been informed about this issue hundreds of times.

thanks to everyone for their reports here. i hope this bug never comes back lol

![image](https://user-images.githubusercontent.com/25624482/99230315-a0597a00-2808-11eb-9d37-3f83905ab90a.png)

**Comment by Skyterix1991** [comment]
@ananjaser1211 

The bug is back for me in V6, but instead of green light and freeze, the phone just restarts. 

PS. The issue was non-present in V5.

I will collect the logs when that happens again.

**Comment by fromage9747** [comment]
2024, running V8. Issue is still occuring. Have to reboot into download mode to resolve. AOD is enabled bit it was off per schedule. Fast charging. I also had it occur whilst AOD was on as well. device locked up and had to be restarted.

**Comment by matinzd** [comment]
Dude please just buy a new phone :)) @fromage9747 
Get over it.

**Comment by fromage9747** [comment]
@matinzd Very helpful.  Why are you even here? The entire point of flashing ROMs is to give old phones new life.  How's about YOU get out of here instead and take your useless comments with you? Capiche?

**Comment by matinzd** [comment]
S7 is kinda dead TBH even with the ROM. @fromage9747
I am still using the Stock Rom but it's not my everyday device.
